// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"MyMenu","status":true,"description":"","parameters":{}},
{"name":"LoadCustomData","status":true,"description":"","parameters":{}}
];
